name: Publish Package
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          git config user.name nullpalette-dev
          git config user.email nullpalette@github.com
          npm version patch
      - uses: actions/setup-node@v3
        with:
          always-auth: true
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm install
      - run: npm run build
      - run: npm publish
      - run: git push
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
