name: Publish Package
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "14.x"
          always-auth: true
          registry-url: "https://npm.pkg.github.com"
          scope: "@TheNullPalette"
      - run: npm ci
      - run: npm run build
      - run: |
          git config user.name nullpalette-dev
          git config user.email nullpalette@github.com
          npm version patch
      - run: cat ./.npmrc
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN_NAMAN }}
      - run: git push
