name: Publish Package
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"
          registry-url: "https://npm.pkg.github.com"
          scope: "TheNullPalette"
      - run: |
          npm install --global yarn
          yarn install
      - run: yarn dist
      - run: |
          git config user.name nullpalette-dev
          git config user.email nullpalette@github.com
          npm version patch
          git push
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN_NAMAN }}