name: Publish Package
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"
          always-auth: true
          registry-url: "https://npm.pkg.github.com"
          scope: "@TheNullPalette"
      - run: yarn
      - run: yarn build
      - run: |
          git config user.name nullpalette-dev
          git config user.email nullpalette@github.com
          npm version patch
      - run: |
          npm publish
          git push
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN_NAMAN }}
